name: Checks

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    name: ${{ matrix.check.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - name: Lint
            command: pnpm lint
          - name: Typecheck
            command: CI=true pnpm typecheck
          - name: Test
            command: pnpm test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ${{ matrix.check.name }}
        run: ${{ matrix.check.command }}
