name: Lighthouse CI

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      url:
        description: "URL to run Lighthouse CI on"
        required: true
        default: "https://mohamedtahiri.vercel.app"

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for Vercel deployment
        if: github.event_name == 'push'
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: vercel_preview_url
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 180
          environment: production
          check_interval: 10

      - name: Run Lighthouse CI and send to Discord
        uses: ./.github/actions/lighthouse-ci
        with:
          url: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.url || steps.vercel_preview_url.outputs.url }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          config-path: ./lighthouserc.json
